//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IrfProject_ko64zx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eredmeny
    {
        public int Eredmeny_Id { get; set; }
        public string Jatekos_nev { get; set; }
        public Nullable<decimal> Eredmeny1 { get; set; }
        public System.DateTime Datum { get; set; }
    }
}
