//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IrfProject_ko64zx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kerdes
    {
        public int Kerdes_Id { get; set; }
        public string Kerdes1 { get; set; }
        public string Valasz_1 { get; set; }
        public string Valasz_2 { get; set; }
        public string Valasz_3 { get; set; }
        public string Valasz_4 { get; set; }
        public int Helyes_valasz { get; set; }
    }
}
