INSERT [dbo].[Kerdes]([Kerdes], [Valasz_1], [Valasz_2], [Valasz_3], [Valasz_4], [Helyes_valasz]) VALUES(N'Mi Brazília fővárosa?', N'Brazíliaváros', N'Salvador', N'Rio de Janeiro', N'Buenos Aires', 1)
INSERT [dbo].[Kerdes]([Kerdes], [Valasz_1], [Valasz_2], [Valasz_3], [Valasz_4], [Helyes_valasz]) VALUES(N'Melyik országban található a Taj Mahal?', N'India', N'Pakisztán', N'Bangladesh', N'Sri Lanka', 1)
INSERT [dbo].[Kerdes]([Kerdes], [Valasz_1], [Valasz_2], [Valasz_3], [Valasz_4], [Helyes_valasz]) VALUES(N'Mi Finnország fővárosa?', N'Helsinki', N'Oslo', N'Tampere', N'Stockholm', 1)
INSERT [dbo].[Kerdes]([Kerdes], [Valasz_1], [Valasz_2], [Valasz_3], [Valasz_4], [Helyes_valasz]) VALUES(N'Kinek volt a legtöbb Oscar jelölése?', N'Meryl Streep', N'Jack Nicholson', N'Katharine Hepburn', N'Ingrid Bergman', 1)
INSERT [dbo].[Kerdes]([Kerdes], [Valasz_1], [Valasz_2], [Valasz_3], [Valasz_4], [Helyes_valasz]) VALUES(N'Ki nyerte a legtöbb aranylabdát?', N'Lionel Messi', N'Cristiano Ronaldo', N'Michel Platini', N'Johan Cruyff', 1)
INSERT [dbo].[Kerdes]([Kerdes], [Valasz_1], [Valasz_2], [Valasz_3], [Valasz_4], [Helyes_valasz]) VALUES(N'Milyen magas a világ legalacsonyabb embere?', N'72 cm', N'67 cm', N'60 cm', N'63 cm', 1)
INSERT [dbo].[Kerdes]([Kerdes], [Valasz_1], [Valasz_2], [Valasz_3], [Valasz_4], [Helyes_valasz]) VALUES(N'Mikor született Roger Federer?', N'1981', N'1983', N'1979', N'1975', 1)
INSERT [dbo].[Kerdes]([Kerdes], [Valasz_1], [Valasz_2], [Valasz_3], [Valasz_4], [Helyes_valasz]) VALUES(N'Mikor született Maradona?', N'1960', N'1946', N'1939', N'1955', 1)
INSERT [dbo].[Kerdes]([Kerdes], [Valasz_1], [Valasz_2], [Valasz_3], [Valasz_4], [Helyes_valasz]) VALUES(N'Hány országgal határos Oroszország?', N'14', N'15', N'16', N'17', 1)
INSERT [dbo].[Kerdes]([Kerdes], [Valasz_1], [Valasz_2], [Valasz_3], [Valasz_4], [Helyes_valasz]) VALUES(N'Melyik országban található a Stonehenge?', N'Wales', N'Skócia', N'Anglia', N'Írország', 3)
INSERT [dbo].[Kerdes]([Kerdes], [Valasz_1], [Valasz_2], [Valasz_3], [Valasz_4], [Helyes_valasz]) VALUES(N'Mi nem kell a palacsintába?', N'Cukor', N'Liszt', N'Tej', N'Élesztő', 4)
INSERT [dbo].[Kerdes]([Kerdes], [Valasz_1], [Valasz_2], [Valasz_3], [Valasz_4], [Helyes_valasz]) VALUES(N'Mi Portugália fővárosa?', N'Porto', N'Lisszabon', N'Madrid', N'Faro', 2)
INSERT [dbo].[Kerdes]([Kerdes], [Valasz_1], [Valasz_2], [Valasz_3], [Valasz_4], [Helyes_valasz]) VALUES(N'Ki volt a gőzgép feltalálója?', N'Robert Fulton', N'James Watt', N'Isaac Newton', N'George Stephenson', 2)
INSERT [dbo].[Kerdes]([Kerdes], [Valasz_1], [Valasz_2], [Valasz_3], [Valasz_4], [Helyes_valasz]) VALUES(N'Ki nyerte a legtöbb Oscar-t?', N'Meryl Streep', N'Jack Nicholson', N'Katharine Hepburn', N'Ingrid Bergman', 3)
INSERT [dbo].[Kerdes]([Kerdes], [Valasz_1], [Valasz_2], [Valasz_3], [Valasz_4], [Helyes_valasz]) VALUES(N'Hová sorolható be a béka?', N'Puhatestű', N'Emlős', N'Hüllő', N'Kétéltű', 4)
INSERT [dbo].[Kerdes]([Kerdes], [Valasz_1], [Valasz_2], [Valasz_3], [Valasz_4], [Helyes_valasz]) VALUES(N'Melyik épület a legmagasabb az alábbiak közül?', N'Shanghai Tower', N'Burj Khalifa', N'Lotte World Tower', N'One World Trade Center', 2)
INSERT [dbo].[Kerdes]([Kerdes], [Valasz_1], [Valasz_2], [Valasz_3], [Valasz_4], [Helyes_valasz]) VALUES(N'A felsoroltak közül, mi Görögország jellegzetes itala?', N'Whiskey', N'Beherovka', N'Ouzo', N'Gin', 3)
INSERT [dbo].[Kerdes]([Kerdes], [Valasz_1], [Valasz_2], [Valasz_3], [Valasz_4], [Helyes_valasz]) VALUES(N'Egy futó hét napon át napi 10 km-t fut. Mennyit fut egy hét alatt összesen?', N'7 km', N'7000 m', N'70000 m', N'700000 m', 3)
INSERT [dbo].[Kerdes]([Kerdes], [Valasz_1], [Valasz_2], [Valasz_3], [Valasz_4], [Helyes_valasz]) VALUES(N'Milyen magas a világ legmagasabb embere?', N'241 cm', N'256 cm', N'251 cm', N'260 cm', 3)
INSERT [dbo].[Kerdes]([Kerdes], [Valasz_1], [Valasz_2], [Valasz_3], [Valasz_4], [Helyes_valasz]) VALUES(N'Melyik évben jelent meg először a Keresztapa című film?', N'1963', N'1972', N'1968', N'1970', 2)
INSERT [dbo].[Kerdes]([Kerdes], [Valasz_1], [Valasz_2], [Valasz_3], [Valasz_4], [Helyes_valasz]) VALUES(N'Mikor született Elton John?', N'1971', N'1965', N'1963', N'1969', 3)
INSERT [dbo].[Kerdes]([Kerdes], [Valasz_1], [Valasz_2], [Valasz_3], [Valasz_4], [Helyes_valasz]) VALUES(N'Mikor lett vége az első világháborúnak?', N'1917', N'1918', N'1919', N'1920', 2)
INSERT [dbo].[Kerdes]([Kerdes], [Valasz_1], [Valasz_2], [Valasz_3], [Valasz_4], [Helyes_valasz]) VALUES(N'Mikor született Shakespeare?', N'1604', N'1564', N'1504', N'1540', 2)
INSERT [dbo].[Kerdes]([Kerdes], [Valasz_1], [Valasz_2], [Valasz_3], [Valasz_4], [Helyes_valasz]) VALUES(N'Mikor alapították az első egyetemet?', N'984', N'1138', N'1104', N'1088', 4)
INSERT [dbo].[Kerdes]([Kerdes], [Valasz_1], [Valasz_2], [Valasz_3], [Valasz_4], [Helyes_valasz]) VALUES(N'Maximum hány játékos tartózkodhat egyszerre a emdencében egy vizilabda meccsen?', N'12', N'13', N'14', N'15', 3)
INSERT [dbo].[Kerdes]([Kerdes], [Valasz_1], [Valasz_2], [Valasz_3], [Valasz_4], [Helyes_valasz]) VALUES(N'Hány Bajnokok Ligája győzelme van a Real Madridnak?', N'10', N'11', N'12', N'13', 4)
INSERT [dbo].[Kerdes]([Kerdes], [Valasz_1], [Valasz_2], [Valasz_3], [Valasz_4], [Helyes_valasz]) VALUES(N'Hány országgal határos Ausztria?', N'4', N'5', N'6', N'7', 4)
